"use client";

import { useState, useMemo, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Share2, Copy, Check, X, Trophy, Calendar, Hash } from "lucide-react";
import type { LeaderboardResponse, ModelsResponse } from "@/lib/api";

interface LeaderboardSnapshotProps {
  leaderboardData: LeaderboardResponse | null;
  modelsData: ModelsResponse | null;
  activeCategory: string | null;
}

export function LeaderboardSnapshot({
  leaderboardData,
  modelsData,
  activeCategory,
}: LeaderboardSnapshotProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const markdownSnapshot = useMemo(() => {
    const now = new Date();
    const dateStr = now.toLocaleDateString("en-IN", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const ranking = leaderboardData?.overallRanking ?? [];
    const top5 = ranking.slice(0, 5);
    const categoryName = activeCategory
      ? leaderboardData?.categories?.find((c) => c.slug === activeCategory)?.name ?? "All"
      : "Overall";

    const lines: string[] = [];
    lines.push("# 🏆 IndicBench Leaderboard Snapshot");
    lines.push("");
    lines.push(`**Category:** ${categoryName}`);
    lines.push(`**Date:** ${dateStr}`);
    lines.push(`**Models Evaluated:** ${ranking.length}`);
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("## Top 5 Models");
    lines.push("");
    lines.push("| Rank | Model | Score |");
    lines.push("|------|-------|-------|");

    for (const entry of top5) {
      lines.push(
        `| ${entry.rank} | ${entry.model.name} (${entry.model.provider}) | ${entry.overallScore.toFixed(1)} |`
      );
    }

    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("*Generated by [IndicBench](https://indicbench.in) — India's AI Benchmark Platform*");

    return lines.join("\n");
  }, [leaderboardData, modelsData, activeCategory]);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(markdownSnapshot);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement("textarea");
      textarea.value = markdownSnapshot;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [markdownSnapshot]);

  const top5 = useMemo(() => {
    const ranking = leaderboardData?.overallRanking ?? [];
    return ranking.slice(0, 5);
  }, [leaderboardData]);

  if (!leaderboardData || top5.length === 0) return null;

  return (
    <>
      {/* Snapshot Button */}
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={() => setIsOpen(true)}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-[rgba(255,255,255,0.06)] text-[#8b8b9e] hover:text-[#f5f5f7] hover:bg-[rgba(255,255,255,0.1)] border border-[rgba(255,255,255,0.06)] transition-all"
        aria-label="Share leaderboard snapshot"
      >
        <Share2 className="h-3.5 w-3.5" />
        Snapshot
      </motion.button>

      {/* Snapshot Panel */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4"
            onClick={() => setIsOpen(false)}
          >
            {/* Backdrop */}
            <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />

            {/* Panel */}
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              transition={{ duration: 0.25, ease: "easeOut" }}
              onClick={(e) => e.stopPropagation()}
              className="relative z-10 w-full max-w-lg glass-card glass-card-gradient-border rounded-2xl overflow-hidden"
            >
              {/* Header */}
              <div className="flex items-center justify-between p-5 border-b border-[rgba(255,255,255,0.06)]">
                <div className="flex items-center gap-2">
                  <div className="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-[#f59e0b15] text-[#f59e0b]">
                    <Trophy className="h-4 w-4" />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-[#f5f5f7]">
                      Leaderboard Snapshot
                    </h3>
                    <p className="text-[10px] text-[#8b8b9e]">
                      Shareable summary of current rankings
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => setIsOpen(false)}
                  className="h-8 w-8 rounded-lg flex items-center justify-center text-[#55556a] hover:text-[#f5f5f7] hover:bg-[rgba(255,255,255,0.06)] transition-all"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>

              {/* Preview */}
              <div className="p-5">
                {/* Meta row */}
                <div className="flex items-center gap-3 mb-4 text-[10px] text-[#8b8b9e]">
                  <div className="flex items-center gap-1">
                    <Calendar className="h-3 w-3" />
                    {new Date().toLocaleDateString("en-IN", {
                      month: "short",
                      day: "numeric",
                      year: "numeric",
                    })}
                  </div>
                  <div className="flex items-center gap-1">
                    <Hash className="h-3 w-3" />
                    {top5.length} models
                  </div>
                  <div className="inline-flex px-2 py-0.5 rounded-full bg-[#10b98115] text-[#10b981] text-[10px] font-medium">
                    {activeCategory
                      ? leaderboardData?.categories?.find(
                          (c) => c.slug === activeCategory
                        )?.name ?? "All"
                      : "Overall"}
                  </div>
                </div>

                {/* Top 5 list */}
                <div className="space-y-2 mb-5">
                  {top5.map((entry, idx) => (
                    <div
                      key={entry.model.id}
                      className="flex items-center gap-3 p-2.5 rounded-lg bg-[rgba(255,255,255,0.03)]"
                    >
                      <div
                        className={`h-7 w-7 rounded-lg flex items-center justify-center text-xs font-bold font-[family-name:var(--font-geist-mono)] ${
                          idx === 0
                            ? "bg-[#fbbf2420] text-[#fbbf24]"
                            : idx === 1
                              ? "bg-[rgba(255,255,255,0.08)] text-[#8b8b9e]"
                              : idx === 2
                                ? "bg-[#f9731620] text-[#f97316]"
                                : "bg-[rgba(255,255,255,0.04)] text-[#55556a]"
                        }`}
                      >
                        #{entry.rank}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="text-sm text-[#f5f5f7] font-medium truncate">
                          {entry.model.name}
                        </div>
                        <div className="text-[10px] text-[#55556a]">
                          {entry.model.provider}
                        </div>
                      </div>
                      <div className="text-sm font-bold font-[family-name:var(--font-geist-mono)] tabular-nums text-[#10b981]">
                        {entry.overallScore.toFixed(1)}
                      </div>
                    </div>
                  ))}
                </div>

                {/* IndicBench branding */}
                <div className="text-center text-[10px] text-[#55556a] mb-4">
                  🇮🇳 IndicBench — India&apos;s AI Benchmark Platform
                </div>

                {/* Markdown preview toggle */}
                <details className="mb-4">
                  <summary className="text-[10px] text-[#8b8b9e] cursor-pointer hover:text-[#f5f5f7] transition-colors">
                    View Markdown Source
                  </summary>
                  <pre className="mt-2 p-3 rounded-lg bg-[rgba(0,0,0,0.3)] text-[10px] text-[#8b8b9e] overflow-x-auto whitespace-pre-wrap max-h-40 overflow-y-auto">
                    {markdownSnapshot}
                  </pre>
                </details>

                {/* Actions */}
                <div className="flex gap-2">
                  <button
                    onClick={handleCopy}
                    className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium bg-[#10b98120] text-[#10b981] border border-[#10b98140] hover:bg-[#10b98130] transition-all"
                  >
                    {copied ? (
                      <>
                        <Check className="h-4 w-4" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="h-4 w-4" />
                        Copy as Markdown
                      </>
                    )}
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
